# Generated by Django 5.2.14 on 2026-05-17 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('product_type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('mug', 'Mug'), ('canvas', 'Canvas'), ('poster', 'Poster'), ('phone_case', 'Phone Case'), ('tote_bag', 'Tote Bag')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_image', models.ImageField(upload_to='mockup-templates/base/')),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to='mockup-templates/masks/')),
                ('shadow_layer', models.ImageField(blank=True, null=True, upload_to='mockup-templates/shadows/')),
                ('highlight_layer', models.ImageField(blank=True, null=True, upload_to='mockup-templates/highlights/')),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('supported_colors', models.JSONField(blank=True, default=list)),
                ('supported_sizes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('product_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MockupRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image_url', models.URLField(blank=True)),
                ('source_prompt', models.TextField(blank=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('variant_color', models.CharField(blank=True, max_length=120)),
                ('variant_size', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='mockup-renders/')),
                ('output_image_url', models.URLField(blank=True)),
                ('processing_notes', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('render_started_at', models.DateTimeField(blank=True, null=True)),
                ('render_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockup_renders', to='generator.generatedimage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockup_renders', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='generator.mockuptemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
