# Generated by Django 5.2.14 on 2026-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_mockuptemplate_mockuprender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuprender',
            name='placement_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
