# Generated by Django 5.2.14 on 2026-05-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('generator', '0003_mockuprender_placement_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuprender',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockup_renders', to='gallery.artwork'),
        ),
        migrations.CreateModel(
            name='SourceDesignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.TextField(blank=True)),
                ('source_fingerprint', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='mockup-source-assets/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_design_assets', to='gallery.artwork')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='mockuprender',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockup_renders', to='generator.sourcedesignasset'),
        ),
    ]
