# Generated by Django 5.2.14 on 2026-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_mockuprender_artwork_sourcedesignasset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedesignasset',
            name='image',
            field=models.ImageField(blank=True, help_text='Leave empty when this asset should inherit the image from the selected artwork.', null=True, upload_to='mockup-source-assets/'),
        ),
        migrations.AlterField(
            model_name='sourcedesignasset',
            name='source_fingerprint',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcedesignasset',
            name='source_url',
            field=models.TextField(blank=True, help_text='Optional original image URL. Only needed when no uploaded image or artwork image is available.'),
        ),
    ]
