# Generated by Django 5.2.14 on 2026-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_sourcedesignasset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuprender',
            name='source_image_url',
            field=models.TextField(blank=True),
        ),
    ]
