# Generated by Django 5.2.14 on 2026-05-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_mockuprender_source_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuprender',
            name='output_image_url',
            field=models.TextField(blank=True),
        ),
    ]
