# Generated by Django 5.2.14 on 2026-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_mockuptemplate_displacement_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuprender',
            name='text_elements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
