# Generated by Django 5.2.16 on 2026-07-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_mockuprender_text_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuprender',
            name='part_name',
            field=models.CharField(blank=True, help_text='Specific part name (e.g. front, back) if rendering a template part.', max_length=30),
        ),
        migrations.AlterField(
            model_name='mockuptemplate',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockup-templates/base/'),
        ),
        migrations.CreateModel(
            name='MockupTemplatePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left_sleeve', 'Left Sleeve'), ('right_sleeve', 'Right Sleeve')], default='front', max_length=30)),
                ('base_image', models.ImageField(upload_to='mockup-templates/parts/base/')),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/masks/')),
                ('displacement_map', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/displacement/')),
                ('shadow_layer', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/shadows/')),
                ('highlight_layer', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/highlights/')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='generator.mockuptemplate')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('template', 'name')},
            },
        ),
    ]
