# Generated by Django 5.2.16 on 2026-07-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_collection_artwork_collection'),
        ('generator', '0011_mockuprender_part_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptemplate',
            name='canvas_height',
            field=models.PositiveIntegerField(blank=True, help_text='Mockup canvas height in pixels, for templates without a root base_image.', null=True),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='canvas_width',
            field=models.PositiveIntegerField(blank=True, help_text='Mockup canvas width in pixels, for templates without a root base_image.', null=True),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='supported_file_formats',
            field=models.JSONField(blank=True, default=list, help_text="Accepted print-file formats, e.g. ['png', 'pdf']."),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='bleed_area',
            field=models.JSONField(blank=True, default=dict, help_text='Bleed as {top, right, bottom, left} in pixels beyond the print area edges.'),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='dpi',
            field=models.PositiveIntegerField(default=300, help_text='Required print resolution for this print area.'),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='print_file_height',
            field=models.PositiveIntegerField(blank=True, help_text='Required print-file height in pixels at the target DPI.', null=True),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='print_file_width',
            field=models.PositiveIntegerField(blank=True, help_text='Required print-file width in pixels at the target DPI.', null=True),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='safe_area',
            field=models.JSONField(blank=True, default=dict, help_text='Safe area as {left, top, width, height} percentages within the print area.'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=120)),
                ('print_provider', models.CharField(blank=True, max_length=120)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('printify_variant_id', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-variants/')),
                ('supported_print_areas', models.JSONField(blank=True, default=list, help_text="Part names this variant supports printing on, e.g. ['front', 'back']. Empty means all template parts.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='generator.mockuptemplate')),
            ],
            options={
                'ordering': ('template', 'colour', 'size'),
                'unique_together': {('template', 'colour', 'size')},
            },
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('selected_colour', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('ordered', 'Ordered'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='design-projects/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_projects', to='generator.mockuptemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_projects', to=settings.AUTH_USER_MODEL)),
                ('selected_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_projects', to='generator.productvariant')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DesignPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left_sleeve', 'Left Sleeve'), ('right_sleeve', 'Right Sleeve')], default='front', max_length=30)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('opacity', models.FloatField(default=1)),
                ('crop_data', models.JSONField(blank=True, default=dict)),
                ('corner_radius', models.FloatField(default=0)),
                ('text_settings', models.JSONField(blank=True, default=list)),
                ('preview_url', models.TextField(blank=True)),
                ('print_file_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_placements', to='gallery.artwork')),
                ('generated_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_placements', to='generator.generatedimage')),
                ('design_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='generator.designproject')),
            ],
            options={
                'ordering': ('design_project', 'product_part'),
                'unique_together': {('design_project', 'product_part')},
            },
        ),
    ]
