# Generated by Django 5.2.16 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_design_projects_and_variants'),
        ('shop', '0003_product_mockup_template'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_template_color_size',
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'template', 'color_name', 'size'), name='unique_product_template_color_size'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True)), fields=('template', 'color_name', 'size'), name='unique_template_color_size_without_product'),
        ),
    ]
