# Generated by Django 5.2.16 on 2026-07-17 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_remove_productvariant_unique_template_color_size_and_more'),
        ('printify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptemplate',
            name='selected_print_provider',
            field=models.ForeignKey(blank=True, help_text="Which synced Printify print provider fulfils this template's variants, if mapped.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockup_templates', to='printify.printifyprintprovider'),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='printify_placeholder_config',
            field=models.JSONField(blank=True, default=dict, help_text="Raw placeholder dimensions/config for this print area from the mapped Printify print provider's variant response."),
        ),
        migrations.AddField(
            model_name='mockuptemplatepart',
            name='printify_placeholder_position',
            field=models.CharField(blank=True, help_text="Printify's placeholder position key for this print area (e.g. 'front', 'sleeve_left') if it differs from `name` — Printify's naming doesn't always match ours 1:1. Falls back to `name` when blank.", max_length=30),
        ),
    ]
