# Generated by Django 5.2.16 on 2026-07-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_mockuptemplate_selected_print_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_file', models.ImageField(blank=True, null=True, upload_to='design-projects/print-files/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('dpi', models.PositiveIntegerField(default=0)),
                ('signature', models.CharField(blank=True, db_index=True, help_text='sha256 of every printable input — see build_print_file_signature(). Used to detect staleness and reuse an existing completed file instead of regenerating.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_print_files', to='generator.designplacement')),
                ('template_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_print_files', to='generator.mockuptemplatepart')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['design_placement', 'signature'], name='generator_g_design__2fd274_idx')],
            },
        ),
    ]
