# Generated by Django 5.2.16 on 2026-07-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_check_no_orphan_variants'),
        ('shop', '0004_remove_product_inventory_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_template_color_size',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_template_color_size_without_product',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, help_text='Known physical stock quantity where supplied. Leave empty for print-on-demand availability — empty inventory with is_available=True means the provider (e.g. Printify) currently offers this variant, just with no numeric stock count given. Never a placeholder like 9999 — empty means genuinely unknown, not unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin reference/display only — NOT read by the pricing engine. apps.cart.pricing.price_item() and apps.shop.services.get_product_starting_price() both compute from base_cost + markup rules; this field is never used as an override.', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'template', 'color_name', 'size'), name='unique_product_template_color_size'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('external_variant_id', ''), _negated=True), fields=('external_provider', 'external_variant_id'), name='unique_external_provider_variant'),
        ),
    ]
