# Generated by Django 5.2.16 on 2026-07-19 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_productvariant_product_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_placements', to='generator.sourcedesignasset'),
        ),
        migrations.AddField(
            model_name='sourcedesignasset',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Original upload size in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='sourcedesignasset',
            name='has_transparency',
            field=models.BooleanField(default=False, help_text='Whether the stored image has an alpha channel (structural check, not per-pixel).'),
        ),
        migrations.AddField(
            model_name='sourcedesignasset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sourcedesignasset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_design_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcedesignasset',
            name='source_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('user_upload', 'User upload'), ('ai_generated', 'AI generated')], default='gallery', max_length=20),
        ),
    ]
