# Generated by Django 5.2.16 on 2026-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_remove_mockuptemplate_base_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockuptemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the name.', unique=True),
        ),
    ]
