# Generated by Django 5.2.16 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_alter_mockuptemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupTemplatePartColorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text="Matches ProductVariant.color_name case-insensitively, e.g. 'Black'.", max_length=100)),
                ('base_image', models.ImageField(upload_to='mockup-templates/parts/colors/base/')),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/colors/masks/')),
                ('displacement_map', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/colors/displacement/')),
                ('shadow_layer', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/colors/shadows/')),
                ('highlight_layer', models.ImageField(blank=True, null=True, upload_to='mockup-templates/parts/colors/highlights/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_assets', to='generator.mockuptemplatepart')),
            ],
            options={
                'ordering': ('color_name',),
                'unique_together': {('part', 'color_name')},
            },
        ),
    ]
