# Generated by Django 5.2.16 on 2026-07-19 08:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generator', '0016_generatedprintfile'),
        ('shop', '0003_product_mockup_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount off'), ('percentage', 'Percentage off')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Total uses across all customers. Blank means unlimited.', null=True)),
                ('max_redemptions_per_user', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('times_redeemed', models.PositiveIntegerField(default=0, help_text='Incremented on completed ORDERS only (Section 5, not built yet) — applying a coupon to a cart never increments this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', help_text='Main selling currency (ISO 4217). Multi-currency conversion is future work — see TODO.md item 29.', max_length=3)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat percentage applied to the post-discount subtotal. Placeholder only — no tax-jurisdiction calculation.', max_digits=5)),
                ('flat_shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('5.99'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Post-discount subtotal at/above which shipping is waived. Blank means no free-shipping offer.', max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.CreateModel(
            name='PrintAreaCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('part_name',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='cart.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=120)),
                ('colour', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('preview_image_url', models.TextField(blank=True)),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict, help_text='Snapshot of the last pricing computation (base cost, print-area charges, markup, warnings) for support/debugging and future checkout re-display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('design_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='generator.designproject')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='shop.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='generator.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('cart', 'design_project'), name='unique_cart_item_per_design_project')],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('global', 'Global (all products)'), ('category', 'Category'), ('product', 'Product-specific')], max_length=20)),
                ('markup_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Flat currency amount if markup_type=fixed, or percentage points (15.00 = 15%) if markup_type=percentage.', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Tie-breaker when more than one active rule of the same rule_type matches; higher wins.')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='shop.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='shop.product')),
            ],
            options={
                'ordering': ('rule_type', '-priority', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('product__isnull', True), ('rule_type', 'global')), models.Q(('category__isnull', False), ('product__isnull', True), ('rule_type', 'category')), models.Q(('category__isnull', True), ('product__isnull', False), ('rule_type', 'product')), _connector='OR'), name='pricingrule_scope_matches_rule_type')],
            },
        ),
    ]
