from django.urls import path

from .views import (
    AdminDesignProjectListView,
    AdminGeneratedImageListView,
    AdminGeneratedPrintFileListView,
    AdminGenerationRequestListView,
    AdminMockupRenderListView,
    AdminMockupTemplateDetailView,
    AdminMockupTemplateListCreateView,
    AdminMockupTemplatePartDetailView,
    AdminMockupTemplatePartListCreateView,
    AdminProductVariantBulkActionView,
    AdminProductVariantDetailView,
    AdminProductVariantListCreateView,
    AdminSourceDesignAssetListView,
    DesignProjectDetailView,
    DesignProjectDuplicateView,
    DesignProjectGeneratePrintFilesView,
    DesignProjectListCreateView,
    DesignProjectPrintFilesView,
    GeneratedImageListView,
    GenerationRequestListCreateView,
    MockupRenderDetailView,
    MockupRenderListCreateView,
    MockupTemplateDetailView,
    MockupTemplateListView,
    ProductVariantListView,
    SourceDesignAssetFromGeneratedImageView,
    SourceDesignAssetUploadView,
)


urlpatterns = [
    path("requests/", GenerationRequestListCreateView.as_view(), name="generation-request-list-create"),
    path("images/", GeneratedImageListView.as_view(), name="generated-image-list"),
    path("mockup-templates/", MockupTemplateListView.as_view(), name="mockup-template-list"),
    path("mockup-templates/<int:pk>/", MockupTemplateDetailView.as_view(), name="mockup-template-detail"),
    path("product-variants/", ProductVariantListView.as_view(), name="product-variant-list"),
    path("design-assets/upload/", SourceDesignAssetUploadView.as_view(), name="source-design-asset-upload"),
    path(
        "design-assets/from-generated-image/",
        SourceDesignAssetFromGeneratedImageView.as_view(),
        name="source-design-asset-from-generated-image",
    ),
    path("mockup-renders/", MockupRenderListCreateView.as_view(), name="mockup-render-list-create"),
    path("mockup-renders/<int:pk>/", MockupRenderDetailView.as_view(), name="mockup-render-detail"),
    path("design-projects/", DesignProjectListCreateView.as_view(), name="design-project-list-create"),
    path("design-projects/<int:pk>/", DesignProjectDetailView.as_view(), name="design-project-detail"),
    path(
        "design-projects/<int:pk>/duplicate/",
        DesignProjectDuplicateView.as_view(),
        name="design-project-duplicate",
    ),
    path(
        "design-projects/<int:pk>/generate-print-files/",
        DesignProjectGeneratePrintFilesView.as_view(),
        name="design-project-generate-print-files",
    ),
    path(
        "design-projects/<int:pk>/print-files/",
        DesignProjectPrintFilesView.as_view(),
        name="design-project-print-files",
    ),
    path(
        "admin/mockup-templates/",
        AdminMockupTemplateListCreateView.as_view(),
        name="admin-mockup-template-list",
    ),
    path(
        "admin/mockup-templates/<int:pk>/",
        AdminMockupTemplateDetailView.as_view(),
        name="admin-mockup-template-detail",
    ),
    path(
        "admin/mockup-template-parts/",
        AdminMockupTemplatePartListCreateView.as_view(),
        name="admin-mockup-template-part-list",
    ),
    path(
        "admin/mockup-template-parts/<int:pk>/",
        AdminMockupTemplatePartDetailView.as_view(),
        name="admin-mockup-template-part-detail",
    ),
    path("admin/product-variants/", AdminProductVariantListCreateView.as_view(), name="admin-product-variant-list"),
    path(
        "admin/product-variants/<int:pk>/",
        AdminProductVariantDetailView.as_view(),
        name="admin-product-variant-detail",
    ),
    path(
        "admin/product-variants/bulk-action/",
        AdminProductVariantBulkActionView.as_view(),
        name="admin-product-variant-bulk-action",
    ),
    path("admin/design-projects/", AdminDesignProjectListView.as_view(), name="admin-design-project-list"),
    path("admin/mockup-renders/", AdminMockupRenderListView.as_view(), name="admin-mockup-render-list"),
    path(
        "admin/generated-print-files/",
        AdminGeneratedPrintFileListView.as_view(),
        name="admin-generated-print-file-list",
    ),
    path(
        "admin/generation-requests/",
        AdminGenerationRequestListView.as_view(),
        name="admin-generation-request-list",
    ),
    path("admin/generated-images/", AdminGeneratedImageListView.as_view(), name="admin-generated-image-list"),
    path(
        "admin/source-design-assets/",
        AdminSourceDesignAssetListView.as_view(),
        name="admin-source-design-asset-list",
    ),
]
