# Generated by Django 5.2.16 on 2026-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_collection_artwork_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the title.', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the name.', unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the name.', unique=True),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the title.', unique=True),
        ),
    ]
