# Generated by Django 5.2.16 on 2026-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_inventory_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the name.', unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate a unique slug from the name.', unique=True),
        ),
    ]
