# Generated by Django 5.2.16 on 2026-07-17 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generator', '0014_remove_productvariant_unique_template_color_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifyBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_id', models.PositiveIntegerField(help_text="Printify's numeric blueprint ID.", unique=True)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='Blueprint preview image URLs from Printify.')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mockup_template', models.ForeignKey(blank=True, help_text='Internal mockup template this blueprint is mapped to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printify_blueprints', to='generator.mockuptemplate')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PrintifySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('blueprints', 'Blueprint list'), ('providers', 'Print providers for one blueprint')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('blueprints_synced', models.PositiveIntegerField(default=0)),
                ('providers_synced', models.PositiveIntegerField(default=0)),
                ('variants_synced', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(blank=True, help_text='Set for a Kind.PROVIDERS run; blank for a full blueprint-list sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='printify.printifyblueprint')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printify_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PrintifyPrintProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField(help_text="Printify's numeric print provider ID.")),
                ('title', models.CharField(max_length=255)),
                ('location', models.JSONField(blank=True, default=dict, help_text='Provider location/country info from Printify.')),
                ('variants', models.JSONField(blank=True, default=list, help_text='Raw variant list: id, title, options (colour/size), placeholders (print-area position + dimensions) per variant.')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_providers', to='printify.printifyblueprint')),
            ],
            options={
                'ordering': ('blueprint', 'title'),
                'constraints': [models.UniqueConstraint(fields=('blueprint', 'provider_id'), name='unique_blueprint_provider')],
            },
        ),
    ]
