# Generated by Django 5.2.16 on 2026-07-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printifysyncrun',
            name='blueprints_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printifysyncrun',
            name='blueprints_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printifysyncrun',
            name='providers_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printifysyncrun',
            name='providers_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
